apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-atm-config
  namespace: smart-atm
data:
  POSTGRES_DB: "atm_db"
  POSTGRES_USER: "atm_user"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
  CORS_ORIGINS: '["*"]'
  DEBUG: "false"
  APP_NAME: "Smart ATM Platform"