apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-atm-config
  namespace: smart-atm
data:
  ENV: "production"
  REDIS_URL: "redis://redis:6379/0"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  REDIS_ENABLED: "true"
  RABBITMQ_ENABLED: "true"
  RATE_LIMIT_PER_MINUTE: "120"